# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
    -   id: black-jupyter
-   repo: https://github.com/PyCQA/pylint
    rev: v2.16.0b0
    hooks:
    -   id: pylint
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.4.0
    hooks:
    -   id: nbqa-pylint
